---
title: "figures-diapause-thesis"
output:
  pdf_document:
    toc: true
  html_document:
    code_folding: show
    toc: true
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ape)
library(ggtree)
library(phangorn)
```


# Make Phylogenetic Tree
```{r}
#Read tree file
tree <- read.nexus("omm_v12_190tax_CDS_tree.nexus")

#Rotate tree so it resembles the one on OrthoMaM webpage
tree2 <- ladderize(tree, right = TRUE)
tree2 <- reorder(tree2, order = "cladewise")

```

```{r}
#Define diapausing species
Obligate <- c("Ailuropoda_melanoleuca", "Dasypus_novemcinctus",
                  "Enhydra_lutris_kenyoni", "Leptonychotes_weddellii",
                  "Mirounga_angustirostris", "Odobenus_rosmarus_divergens",
                  "Ursus_maritimus", "Zalophus_californianus", 
                  "Callorhinus_ursinus", "Eumetopias_jubatus", 
                  "Halichoerus_grypus", "Lontra_canadensis", "Meles_meles",
                  "Mirounga_leonina", "Mustela_erminea", "Phoca_vitulina", 
                  "Ursus_americanus", "Ursus_arctos")
Facultative <- c("Meriones_unguiculatus", "Rattus_norvegicus", 
                 "Mus_musculus", "Peromyscus_maniculatus_bairdii", 
                 "Peromyscus_leucopus", "Sorex_araneus")


#Define all species within each Superorder
Monotremata <- c("Tachyglossus_aculeatus", "Ornithorhynchus_anatinus")

Marsupialia <- c("Monodelphis_domestica", "Gracilinanus_agilis",
  "Dromiciops_gliroides", "Antechinus_flavipes", "Sarcophilus_harrisii",
  "Trichosurus_vulpecula", "Phascolarctos_cinereus", "Vombatus_ursinus")

Xenarthra <- c( "Choloepus_didactylus", "Dasypus_novemcinctus")

Afrotheria <- c( "Trichechus_manatus_latirostris", "Elephas_maximus_indicus",
  "Loxodonta_africana", "Orycteropus_afer_afer", "Elephantulus_edwardii",
  "Echinops_telfairi", "Chrysochloris_asiatica")

Euarchonta <- c("Galeopterus_variegatus", "Tupaia_chinensis",
  "Otolemur_garnettii", "Propithecus_coquereli", "Microcebus_murinus",
  "Lemur_catta", "Carlito_syrichta", "Aotus_nancymaae", "Callithrix_jacchus",
  "Saimiri_boliviensis_boliviensis", "Sapajus_apella", "Cebus_imitator",
  "Hylobates_moloch", "Nomascus_leucogenys", "Pongo_abelii",
  "Gorilla_gorilla_gorilla", "Homo_sapiens", "Pan_troglodytes", 
  "Pan_paniscus", "Colobus_angolensis_palliatus", "Piliocolobus_tephrosceles",
  "Trachypithecus_francoisi", "Rhinopithecus_roxellana", "Rhinopithecus_bieti",
  "Chlorocebus_sabaeus", "Macaca_nemestrina", "Macaca_thibetana_thibetana",
  "Macaca_fascicularis", "Macaca_mulatta", "Mandrillus_leucophaeus",
  "Cercocebus_atys", "Papio_anubis", "Theropithecus_gelada")

Glires <- c("Oryctolagus_cuniculus", "Ochotona_curzoniae", "Ochotona_princeps",
  "Heterocephalus_glaber", "Fukomys_damarensis", "Cavia_porcellus",
  "Chinchilla_lanigera", "Octodon_degus", "Urocitellus_parryii",
  "Ictidomys_tridecemlineatus", "Marmota_marmota_marmota", 
  "Marmota_monax", "Marmota_flaviventris", "Castor_canadensis",
  "Perognathus_longimembris_pacificus", "Dipodomys_spectabilis",
  "Dipodomys_ordii", "Jaculus_jaculus", "Nannospalax_galili",
  "Acomys_russatus", "Meriones_unguiculatus", "Rattus_norvegicus",
  "Rattus_rattus", "Grammomys_surdaster", "Arvicanthis_niloticus",
  "Apodemus_sylvaticus", "Mastomys_coucha", "Mus_pahari",
  "Mus_musculus", "Mus_caroli", "Onychomys_torridus",
  "Peromyscus_californicus_insignis", "Peromyscus_maniculatus_bairdii",
  "Peromyscus_leucopus", "Phodopus_roborovskii", "Cricetulus_griseus",
  "Mesocricetus_auratus", "Myodes_glareolus", "Arvicola_amphibius",
  "Microtus_fortis", "Microtus_ochrogaster", "Microtus_oregoni")

Laurasiatheria <- c( "Talpa_occidentalis", "Condylura_cristata",
  "Erinaceus_europaeus", "Suncus_etruscus", "Sorex_araneus",
  "Rhinolophus_ferrumequinum", "Hipposideros_armiger",
  "Rousettus_aegyptiacus", "Pteropus_alecto", "Pteropus_vampyrus",
  "Pteropus_giganteus", "Desmodus_rotundus", "Phyllostomus_discolor",
  "Phyllostomus_hastatus", "Artibeus_jamaicensis", "Sturnira_hondurensis",
  "Molossus_molossus", "Miniopterus_natalensis", "Pipistrellus_kuhlii",
  "Eptesicus_fuscus", "Myotis_davidii", "Myotis_myotis", "Myotis_lucifugus",
  "Myotis_brandtii", "Ceratotherium_simum_simum", "Equus_asinus",
  "Equus_quagga", "Equus_caballus", "Equus_przewalskii", "Vicugna_pacos",
  "Camelus_dromedarius", "Camelus_ferus", "Camelus_bactrianus",
  "Sus_scrofa", "Odocoileus_virginianus_texanus", "Cervus_canadensis",
  "Cervus_elaphus", "Oryx_dammah", "Budorcas_taxicolor", "Capra_hircus", 
  "Ovis_aries", "Bubalus_bubalis", "Bison_bison_bison", "Bos_mutus",
  "Bos_taurus", "Bos_indicus", "Balaenoptera_musculus", 
  "Balaenoptera_acutorostrata_scammoni", "Physeter_catodon",
  "Lipotes_vexillifer", "Monodon_monoceros", "Delphinapterus_leucas",
  "Neophocaena_asiaeorientalis_asiaeorientalis", "Phocoena_sinus",
  "Orcinus_orca", "Lagenorhynchus_obliquidens", "Tursiops_truncatus",
  "Globicephala_melas", "Manis_pentadactyla", "Manis_javanica",
  "Hyaena_hyaena", "Suricata_suricatta", "Panthera_tigris", "Panthera_uncia",
  "Panthera_leo", "Panthera_pardus", "Leopardus_geoffroyi", "Felis_catus",
  "Lynx_canadensis", "Prionailurus_bengalensis", "Acinonyx_jubatus",
  "Puma_yagouaroundi", "Puma_concolor", "Canis_lupus_dingo", "Vulpes_lagopus",
  "Vulpes_vulpes", "Meles_meles", "Lontra_canadensis", "Enhydra_lutris_kenyoni",
  "Neogale_vison", "Mustela_erminea", "Mustela_putorius_furo", 
  "Ailuropoda_melanoleuca", "Ursus_americanus", "Ursus_maritimus",
  "Ursus_arctos", "Odobenus_rosmarus_divergens", "Callorhinus_ursinus",
  "Zalophus_californianus", "Eumetopias_jubatus", "Phoca_vitulina",
  "Halichoerus_grypus", "Neomonachus_schauinslandi", "Leptonychotes_weddellii",
  "Mirounga_leonina", "Mirounga_angustirostris")

#Define species within subset for analysis
subset <- c("Choloepus_didactylus", "Dasypus_novemcinctus",
            "Trichechus_manatus_latirostris", "Elephas_maximus_indicus",
            "Elephantulus_edwardii", "Echinops_telfairi",
            "Meriones_unguiculatus", "Rattus_norvegicus", "Rattus_rattus",
            "Grammomys_surdaster", "Mastomys_coucha", "Mus_pahari",
            "Mus_musculus", "Mus_caroli", "Onychomys_torridus",
            "Peromyscus_californicus_insignis",
            "Peromyscus_maniculatus_bairdii", "Peromyscus_leucopus",
            "Mesocricetus_auratus", "Arvicola_amphibius", "Microtus_fortis",
            "Talpa_occidentalis", "Condylura_cristata",
            "Erinaceus_europaeus", "Suncus_etruscus", "Sorex_araneus",
            "Canis_lupus_dingo", "Vulpes_vulpes", "Meles_meles",
            "Lontra_canadensis", "Enhydra_lutris_kenyoni", "Neogale_vison",
            "Mustela_erminea", "Ailuropoda_melanoleuca", "Ursus_americanus",
            "Ursus_maritimus", "Ursus_arctos", "Odobenus_rosmarus_divergens",
            "Callorhinus_ursinus", "Zalophus_californianus",
            "Eumetopias_jubatus", "Halichoerus_grypus", 
            "Neomonachus_schauinslandi", "Leptonychotes_weddellii",
            "Mirounga_leonina", "Mirounga_angustirostris")

#Define which node is the root of each subtree corresponding to a Superorder
node_Marsupialia <- getMRCA(tree2, Marsupialia)
node_Afrotheria  <- getMRCA(tree2, Afrotheria)
node_Glires      <- getMRCA(tree2, Glires)
node_Laurasiatheria <- getMRCA(tree2, Laurasiatheria)
node_Xenarthra   <- getMRCA(tree2, Xenarthra)
node_Monotremata <- getMRCA(tree2, Monotremata)
node_Euarchonta <- getMRCA(tree2, Euarchonta)

```

```{r}
#Define a function to get all clade nodes for coloring
get_clade_nodes <- function(tree, node) {
  clade <- node
  added <- TRUE
  
  while (added) {
    added <- FALSE
    
    children <- tree$edge[tree$edge[,1] %in% clade, 2]
    new <- setdiff(children, clade)
    
    if (length(new) > 0) {
      clade <- c(clade, new)
      added <- TRUE }
  }
  
  clade }


#Get all clade nodes for each Superorder
desc_Ma <- get_clade_nodes(tree2, node_Marsupialia)
desc_X <- get_clade_nodes(tree2, node_Xenarthra)
desc_Mo <- get_clade_nodes(tree2, node_Monotremata)
desc_Ma <- get_clade_nodes(tree2, node_Marsupialia)
desc_A <- get_clade_nodes(tree2, node_Afrotheria)
desc_L <- get_clade_nodes(tree2, node_Laurasiatheria)
desc_G <- get_clade_nodes(tree2, node_Glires)
desc_E <- get_clade_nodes(tree2, node_Euarchonta)

```

```{r}
# Color diapausing species
tip_colors <- rep("black", length(tree2$tip.label))
names(tip_colors) <- tree2$tip.label
tip_colors[tree2$tip.label %in% Obligate] <- "blue"
tip_colors[tree2$tip.label %in% Facultative] <- "red"

#Color branches in each of the Superorder subtrees
edge_colors <- rep("black", nrow(tree2$edge))
edge_colors[tree2$edge[,2] %in% desc_X] <- "#FBC02D"
edge_colors[tree2$edge[,2] %in% desc_Mo] <- "#9E9E9E"
edge_colors[tree2$edge[,2] %in% desc_Ma] <- "#EC407A"
edge_colors[tree2$edge[,2] %in% desc_A] <- "#F44336"
edge_colors[tree2$edge[,2] %in% desc_L] <- "#4CAF50"
edge_colors[tree2$edge[,2] %in% desc_G] <- "#1976D2"
edge_colors[tree2$edge[,2] %in% desc_E] <- "#7B1FA2"

#Mark subset of species
star_tips <- which(tree2$tip.label %in% subset)

```

```{r}
#Plot the tree
plot(tree2,
     type = "fan",
     rotate.tree = 180,
     edge.color = edge_colors,
     tip.color = tip_colors,
     cex = 0.5)

# Add stars
tiplabels(pch = 8,
          tip = star_tips,
          col = "gold",
          cex = 0.5,
          offset = -0.005)
```

```{r}
#Save tree as png (vertical version)
png("tree1.png",
    width = 2480,
    height = 3508,
    res = 300)

par(mar = c(5, 1, 5, 1), xpd = NA)

plot(tree2,
     type = "fan",
     rotate.tree = 180,
     edge.color = edge_colors,
     tip.color = tip_colors,
     cex = 0.3)

# Add stars
tiplabels(pch = 8,
          tip = star_tips,
          col = "gold",
          cex = 0.5,
          offset = -0.005)

usr <- par("usr")

mtext("Mammalian Phylogeny",
      side = 3,
      line = 1,
      cex = 2,
      font = 2)

legend("topleft",
       legend = c("Monotremata", "Marsupialia", "Xenarthra",
                  "Afrotheria", "Euarchonta", "Glires", "Laurasiatheria"),
       col = c("#9E9E9E", "#EC407A", "#FBC02D", "#F44336",
               "#7B1FA2", "#1976D2", "#4CAF50"),
       lwd = 4,
       bty = "n",
       cex = 0.7)

legend("topright",
       legend = c("Facultative", "Obligate"),
       col = c("red", "blue"),
       pch = 19,
       bty = "n",
       cex = 0.7)

text(x = usr[1],
     y = usr[4] + 0.01 * diff(usr[3:4]),
     labels = "Superorder:",
     adj = c(0, 1),
     font = 2,
     cex = 0.8)

text(x = usr[2],
     y = usr[4] + 0.01 * diff(usr[3:4]),
     labels = "Type of Diapause:",
     adj = c(1, 1),
     font = 2,
     cex = 0.8)

dev.off()

```

```{r}
#Save tree as png (horizontal version)
png("tree2.png",
    width = 3508,
    height = 2480,
    res = 300)

layout(matrix(c(1, 2), nrow = 1), widths = c(5, 1))  # more space for tree

# --- LEFT PANEL: TREE ---
par(mar = c(2, 1, 3, 1), xpd = NA)

plot(tree2,
     type = "fan",
     rotate.tree = 180,
     edge.color = edge_colors,
     tip.color = tip_colors,
     cex = 0.4)

# Add stars
tiplabels(pch = 8,
          tip = star_tips,
          col = "gold",
          cex = 0.5,
          offset = -0.005)

mtext("Mammalian Phylogeny",
      side = 3,
      line = 1,
      cex = 2,
      font = 2)

# --- RIGHT PANEL: LEGENDS ---
par(mar = c(2, 1, 3, 1))
plot.new()

legend(0, 0.72,
       legend = c("Monotremata", "Marsupialia", "Xenarthra",
                  "Afrotheria", "Euarchonta", "Glires", "Laurasiatheria"),
       col = c("#9E9E9E", "#EC407A", "#FBC02D", "#F44336",
               "#7B1FA2", "#1976D2", "#4CAF50"),
       lwd = 4,
       bty = "n",
       cex = 0.9,
       title = "Superorder:",
       title.adj = 0,
       title.font = 2)

legend(0, 0.42,
       legend = c("Facultative", "Obligate"),
       col = c("red", "blue"),
       pch = 19,
       bty = "n",
       cex = 0.9,
       title = "Type of Diapause:",
       title.adj = 0,
       title.font = 2)

dev.off()

```



# Plot of time vs. number species coloured by length of sequence
```{r}
#Read data
time <- read.table("time.txt", header = TRUE)
```

```{r}
#Create bins of length for coloring
time$Length_group <- cut(
  time$Length,
  breaks = c(-Inf, 500, 1500, Inf),
  labels = c("<500", "500-1500", ">1500"))

#Plot time vs. number of species
ggplot(time, aes(x = Time, y = Species, color = Length_group)) +
  geom_point(size = 2.5) +
  
  scale_colour_manual(
    name = "Length of \nsequence",
    values = c(
      "<500" = "#9ECAE1",
      "500-1500" = "#4292C6",
      ">1500" = "#0B3C78")) +
  
  scale_x_continuous(
    expand = c(0, 0), 
    limits = c(0, 2750),
    breaks = seq(0, 2750, by = 500)) +
  scale_y_continuous(
    expand = c(0, 0), 
    limits = c(0, 200),
      breaks = seq(0, 200, by = 50)) +
  
  labs(
    title = "Time consumption vs. number of species",
    x = "Time (min)",
    y = "Number of species") +
  
  theme_minimal()+
    theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5))

```



# Histograms of omega value differences
```{r}
#Read data
df <- read.table("data.txt", header = TRUE)

#Make new columns for differences
df <- df %>%
  mutate(
    ω_1_sub_ω_0 = df$alt_ω_1-df$alt_ω_0,
    ω_2_sub_ω_0 = df$alt_ω_2-df$alt_ω_0)

#Define gene "types"
pluripontency <- c("NANOG", "POU5F1", "SOX2")

control <- c("ACTR1A", "DDIT4", "DOOST", "EHF", "EVPL", 
             "GAS7", "MAP1B", "MRPL27","MYO1A", "NPAS4", 
             "PAFAH1B3", "PAQR3", "PHF24",  "POLR1C", "QRICH1", 
             "TGFB3", "TGM1", "USH1C", "ZC3HC1", "ZCCHC17")

test1 <- c("IGF1", "IGF2", "IGF1R", "IGF2R", "IGFBP2", "IGFBP4", 
           "IGFBP5", "STC1", "STC2", "PAPPA", "PAPPA2")

test2 <- c("HDHD2", "HADH", "HK2", "PSMA7", "COX17", 
           "COX5A", "ABAT", "DAP", "CAPZB", "PMPCA")

#Make new columns for gene "types"
df <- df %>%
  mutate(
    Group1 = case_when(
      Gene %in% pluripontency ~ "pluripotency",
      Gene %in% test1 ~ "test1",
      Gene %in% test2 ~ "test2",
      Gene %in% control ~ "control",
      TRUE ~ "None")) %>%
  mutate(
    Group2 = case_when(
      Gene %in% pluripontency ~ "control",
      Gene %in% test1 ~ "test",
      Gene %in% test2 ~ "test",
      Gene %in% control ~ "control",
      TRUE ~ "None"))

```

```{r}
#Convert to long format for plotting
plot_df_all <- df %>%
  pivot_longer(
    cols = c(`ω_1_sub_ω_0`, `ω_2_sub_ω_0`),
    names_to = "variable",
    values_to = "value")

#Find mean and median
stats_df <- plot_df_all %>%
  group_by(Group2, variable) %>%
  summarise(
    mean_value = mean(value, na.rm = TRUE),
    median_value = median(value, na.rm = TRUE),
    .groups = "drop")

```

```{r}
#Plot histogram of omega differences for test and control genes
ggplot(plot_df_all, aes(x = value)) +
  geom_vline(xintercept = 0, linewidth = 0.3) +
  
  geom_histogram(bins = 25,
                 fill = "steelblue",
                 color = "black") +
  
  geom_vline(data = stats_df,
    aes(xintercept = mean_value),
    colour = "darkgreen",
    linewidth = 0.3,
    linetype = "dashed") +
  
  facet_grid(
    Group2 ~ variable,
    labeller = labeller(
      variable = c(
        "ω_1_sub_ω_0" = "Obligate as foreground",
        "ω_2_sub_ω_0" = "Facultative as foreground"))) +
  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 7.5)) +
  
  labs(
    title = "Distribution of difference in omega values",
    subtitle = "Foreground ω minus background ω",
    x = "Omega value difference",
    y = "Number of Genes") +
  
  theme_minimal()+
      
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5))

```

```{r}
#Filter for only test genes + convert to long format for plotting
plot_df <- df %>%
  filter(Group1 %in% c("test1", "test2")) %>%
  pivot_longer(
    cols = c(`ω_1_sub_ω_0`, `ω_2_sub_ω_0`),
    names_to = "variable",
    values_to = "value")

#Find mean and median
stats_df2 <- plot_df %>%
  group_by(Group1, variable) %>%
  summarise(
    mean_value = mean(value, na.rm = TRUE),
    median_value = median(value, na.rm = TRUE),
    .groups = "drop")

```

```{r}
#Plot histogram of omega differences for test and control genes
ggplot(plot_df, aes(x = value)) +
  geom_vline(xintercept = 0, linewidth = 0.3) +
  
  geom_histogram(bins = 25,
                 fill = "steelblue",
                 color = "black") +
  
  geom_vline(data = stats_df2,
    aes(xintercept = mean_value),
    colour = "darkgreen",
    linewidth = 0.3,
    linetype = "dashed") +
  
  facet_grid(
    Group1 ~ variable,
    labeller = labeller(
      value = c(
        "test1" = "IGF signalling",
        "test2" = "Upregulated"),
      variable = c(
        "ω_1_sub_ω_0" = "Obligate as foreground",
        "ω_2_sub_ω_0" = "Facultative as foreground"))) +
  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 3.5)) +
  
  labs(
    title = "Distribution of difference in omega values",
    subtitle = "Foreground ω minus background ω",
    x = "Omega value difference",
    y = "Number of Genes") +
  
  theme_minimal() +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5))

```



# Omega0 vs. Omega1
## Sign test
```{r}
#Find total number of genes
n = nrow(df)
#Expected frequency of "successes" (foreground ω above background ω) is 0.5 (=22) 

#Find number of "successes" for Obligate species aka ω_1 values above ω_0
ω_1_succes <- sum(df$ω_1_sub_ω_0 > 0)
#This is above the expected number of 22

#Probability of 25 or more successes
#lower.tail = FALSE the probability of >q successes is calculated, so to include q you need to write q-1
pbinom(q = ω_1_succes-1, size = n, prob = 0.5, lower.tail = FALSE)
#Non-significant


#Find number of "successes" for Facultative species aka ω_2 values above ω_0
ω_2_succes <- sum(df$ω_2_sub_ω_0 > 0)
#Below the expected number of 22

#Probability of 8 or less successes
#lower.tail = TRUE the probability of <=q successes is calculated
pbinom(q = ω_2_succes, size = n, prob = 0.5, lower.tail = TRUE)
#Significant



```

## Scatterplot
```{r}
#Convert to long format for plotting
plot_df_all2 <- df %>%
  pivot_longer(
    cols = c(alt_ω_1, alt_ω_2),
    names_to = "Comparison",
    values_to = "Y_value"
  )

#Save pvals for plotting
pvals <- data.frame(
  Comparison = c("alt_ω_1", "alt_ω_2"),
  x = c(0.19, 0.285),
  y = c(0.385, 0.21),
  label = c(
    "italic(p)==0.2256904",
    "italic(p)==1.27243e-05"
  )
)
```

```{r}
#Plot omega0 vs. omega1
ggplot(plot_df_all2, aes(x = alt_ω_0, y = Y_value)) +
  geom_point(aes(colour = Group1), size = 2) +
  
  geom_segment(aes(x = 0, y = 0,
                   xend = 0.45, yend = 0.45,
                   linetype = "ω_0 = ω_1"),
               color = "black",
               linewidth = 0.5) +
  
  geom_smooth(aes(linetype = "Trend line", color = "Trend line"),
              method = "lm", formula = y ~ x + 0, se = FALSE, 
              color = "firebrick", linewidth = 0.7) +
  
  scale_linetype_manual(
    name = "Lines",
    breaks = c("Trend line", "ω_0 = ω_1"),
    values = c("Trend line" = "solid", "ω_0 = ω_1" = "dashed")
    )+ 

  facet_grid(. ~ Comparison,
             labeller = labeller(
               Comparison = c(
                 "alt_ω_1" = "Obligate",
                 "alt_ω_2" = "Facultative"))) +
  
  scale_colour_manual(
    name = "Gene",
    values = c(
      "pluripotency" = "#0B3C78",
      "test1" = "#238B45",
      "test2" = "#74C476",
      "control" = "#4292C6"),
    labels = c(
      "pluripotency" = "Pluripotency",
      "test1" = "IGF signalling",
      "test2" = "Fu et al.",
      "control" = "Control")) +
  
  guides( colour = guide_legend(order = 1),
          linetype = guide_legend(order = 2))+
 
  
  scale_x_continuous(expand = c(0, 0), limits = c(0, 0.45)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.45)) +
  
  labs(
    title = "Comparison of omega values",
    x = "ω_0",
    y = "ω_1") +
  geom_text(
    data = pvals,
    aes(x = x, y = y, label = label),
    parse = TRUE,
    inherit.aes = FALSE, hjust = 0
) +
  
  theme_minimal()+
    theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5))

```






